name: unilostitem-prod
services:
  seq:
    image: datalust/seq:latest
    container_name: seq-unilostitem-prod
    env_file:
      - prod.env
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: unilostitem-api:prod
    container_name: api-unilostitem-prod
    env_file:
      - prod.env
    ports:
      - "8080:8080"
    depends_on:
      - seq
    restart: unless-stopped

volumes:
  seq-data:
    driver: local
